package com.mobileskills.randomapp;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.content.res.Resources;
import android.os.Bundle;
import android.view.View;
import android.widget.Adapter;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.ListView;
import android.widget.RelativeLayout;

import java.util.List;

public class MainActivity extends AppCompatActivity {
    /**
     * This app will have one main activity that will display two buttons.
     * One button will show a view to generate a random number between two numbers choosen by the user.
     * The other button will show a list with numbers generated by the user.
     *
     * */

    ListView myListView;
    String[] numbers = {};
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Button numberGenBtn = (Button) findViewById(R.id.generarNumBtn);
        numberGenBtn.setOnClickListener(new View.OnClickListener() { // button to generate a random number
            @Override
            public void onClick(View v) {
                Intent startIntent = new Intent(getApplicationContext(), NumberGen.class);
                startActivity(startIntent);
            }
        });

        Button numberListBtn = (Button) findViewById(R.id.listNumBtn);
        numberListBtn.setOnClickListener(new View.OnClickListener() { // button to show a list of numbers
            @Override
            public void onClick(View v) {
                Resources res = getResources(); // get the resources from the app
                myListView = (ListView) findViewById(R.id.myListView); // get the list view from the layout
                numbers = res.getStringArray(R.array.numbers);// get the numbers from the array
                System.out.println(numbers.toString());
                ArrayAdapter<CharSequence> aa = new ArrayAdapter<CharSequence>(getApplicationContext(), android.R.layout.activity_list_item, numbers);
                myListView.setAdapter(aa);
                Intent startIntent = new Intent(getApplicationContext(), numberListView.class);
                startIntent.putExtra("com.mobileskills.randomapp.numbers", numbers);
                System.out.println("se ejecuto el intent");
                startActivity(startIntent);
            }
        });
    }
}