package com.mobileskills.randomapp;

import android.content.Intent;
import android.content.res.Resources;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.ListView;

import androidx.appcompat.app.AppCompatActivity;

import java.util.ArrayList;

public class MainActivity extends AppCompatActivity {
    /**
     * This app will have one main activity that will display two buttons.
     * One button will show a view to generate a random number between two numbers choosen by the user.
     * The other button will show a list with numbers generated by the user.
     *
     * */

    ListView myListView;
    ArrayList numbers = new ArrayList<String>();
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Button numberGenBtn = (Button) findViewById(R.id.generarNumBtn);
        numberGenBtn.setOnClickListener(new View.OnClickListener() { // button to generate a random number
            @Override
            public void onClick(View v) {
                Intent startIntent = new Intent(getApplicationContext(), NumberGen.class);
                startActivity(startIntent);
            }
        });

        Button numberListBtn = (Button) findViewById(R.id.listNumBtn);
        numberListBtn.setOnClickListener(new View.OnClickListener() { // button to show a list of numbers
            @Override
            public void onClick(View v) {
                Resources res = getResources();
                Intent numberList = new Intent(getApplicationContext(), numberListView.class);
                startActivity(numberList);
            }
        });
    }
}